import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface ExportPdfOptions {
  title: string
  subtitle?: string
  columns: { header: string; key: string }[]
  data: Record<string, unknown>[]
  filename: string
  businessName?: string
  orientation?: 'portrait' | 'landscape'
}

export async function exportToPdf({
  title, subtitle, columns, data, filename,
  businessName, orientation = 'portrait'
}: ExportPdfOptions): Promise<void> {
  const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' })

  // Header
  const pageWidth = doc.internal.pageSize.getWidth()
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text(businessName || 'BizCore', pageWidth / 2, 15, { align: 'center' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(12)
  doc.text(title, pageWidth / 2, 23, { align: 'center' })

  if (subtitle) {
    doc.setFontSize(9)
    doc.setTextColor(100)
    doc.text(subtitle, pageWidth / 2, 29, { align: 'center' })
    doc.setTextColor(0)
  }

  // Table
  const headers = columns.map((c) => c.header)
  const rows = data.map((row) => columns.map((c) => String(row[c.key] ?? '')))

  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: subtitle ? 34 : 28,
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 9
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { left: 14, right: 14 }
  })

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(
      `Generated by BizCore | Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: 'center' }
    )
  }

  // Save
  const result = await window.api.invoke('dialog:save-file', {
    defaultPath: `${filename}.pdf`,
    filters: [{ name: 'PDF Files', extensions: ['pdf'] }]
  })

  if (result.filePath) {
    doc.save(result.filePath)
  } else {
    doc.save(`${filename}.pdf`)
  }
}
